/*
  # Complete Protocol State Setup for Pending Image Resume

  Apply this migration via Supabase Dashboard SQL Editor

  This migration is safe to run multiple times - it checks for existing columns/constraints.

  1. Creates Protocol State Columns (if they don't exist)
    - protocol_state: Track current state in ESP32-CAM MQTT protocol flow
    - server_image_name: Image name generated by server
    - ack_sent_at, snap_sent_at, sleep_sent_at: Protocol timing

  2. Protocol States
    - hello_received: Device sent HELLO
    - ack_sent: Server sent ACK
    - ack_pending_sent: Server sent ACK to resume pending image transfer (NEW)
    - snap_sent: Server sent SNAP command
    - metadata_received: Got metadata, receiving chunks
    - complete: Image complete, SLEEP sent
    - failed: Protocol flow failed
    - sleep_only: Just send SLEEP (no schedule/unmapped)
*/

-- Step 1: Add protocol state tracking columns if they don't exist
ALTER TABLE device_wake_payloads
ADD COLUMN IF NOT EXISTS protocol_state TEXT;

ALTER TABLE device_wake_payloads
ADD COLUMN IF NOT EXISTS server_image_name TEXT;

ALTER TABLE device_wake_payloads
ADD COLUMN IF NOT EXISTS ack_sent_at TIMESTAMPTZ;

ALTER TABLE device_wake_payloads
ADD COLUMN IF NOT EXISTS snap_sent_at TIMESTAMPTZ;

ALTER TABLE device_wake_payloads
ADD COLUMN IF NOT EXISTS sleep_sent_at TIMESTAMPTZ;

-- Step 2: Drop existing constraint (if it exists)
ALTER TABLE device_wake_payloads
DROP CONSTRAINT IF EXISTS device_wake_payloads_protocol_state_check;

-- Step 3: Add updated constraint with ALL states including new ack_pending_sent
ALTER TABLE device_wake_payloads
ADD CONSTRAINT device_wake_payloads_protocol_state_check
CHECK (protocol_state IN (
  'hello_received',
  'ack_sent',
  'ack_pending_sent',  -- NEW: ACK sent for pending image resume
  'snap_sent',
  'metadata_received',
  'complete',
  'failed',
  'sleep_only'
));

-- Step 4: Create index for protocol state queries (if not exists)
CREATE INDEX IF NOT EXISTS idx_device_wake_payloads_protocol_state
  ON device_wake_payloads(protocol_state, device_id, captured_at DESC);

-- Step 5: Migrate existing data (only if protocol_state is null)
UPDATE device_wake_payloads
SET protocol_state = 'complete'
WHERE protocol_state IS NULL
  AND image_status = 'complete'
  AND image_id IS NOT NULL;

UPDATE device_wake_payloads
SET protocol_state = 'failed'
WHERE protocol_state IS NULL
  AND image_status = 'failed';

UPDATE device_wake_payloads
SET protocol_state = 'metadata_received'
WHERE protocol_state IS NULL
  AND image_status = 'receiving';

UPDATE device_wake_payloads
SET protocol_state = 'complete'
WHERE protocol_state IS NULL
  AND payload_status = 'complete'
  AND (image_id IS NULL OR image_status IS NULL);

UPDATE device_wake_payloads
SET protocol_state = 'hello_received'
WHERE protocol_state IS NULL;

-- Step 6: Add comments
COMMENT ON COLUMN device_wake_payloads.protocol_state IS 'Current state in device wake protocol flow. States: hello_received, ack_sent, ack_pending_sent (resume), snap_sent, metadata_received, complete, failed, sleep_only';
COMMENT ON COLUMN device_wake_payloads.server_image_name IS 'Server-assigned image filename for tracking';
COMMENT ON COLUMN device_wake_payloads.ack_sent_at IS 'Timestamp when ACK was sent to device';
COMMENT ON COLUMN device_wake_payloads.snap_sent_at IS 'Timestamp when SNAP command was sent';
COMMENT ON COLUMN device_wake_payloads.sleep_sent_at IS 'Timestamp when SLEEP command was sent';
