-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.async_error_logs (
  log_id bigint NOT NULL DEFAULT nextval('async_error_logs_log_id_seq'::regclass),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  table_name text NOT NULL,
  trigger_name text NOT NULL,
  function_name text NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb,
  http_method text,
  endpoint text,
  status text NOT NULL DEFAULT 'error'::text,
  error_message text,
  error_details jsonb,
  request_id bigint,
  retry_count integer NOT NULL DEFAULT 0,
  next_retry_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT async_error_logs_pkey PRIMARY KEY (log_id)
);
CREATE TABLE public.companies (
  company_id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  website character varying,
  logo_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  default_weather USER-DEFINED DEFAULT 'Clear'::weather_enum,
  CONSTRAINT companies_pkey PRIMARY KEY (company_id)
);
CREATE TABLE public.company_alert_prefs (
  company_id uuid NOT NULL,
  thresholds jsonb NOT NULL DEFAULT '{"mgi": {"absolute_high": 0.60, "velocity_high": 0.25, "absolute_critical": 0.80, "velocity_critical": 0.40, "speed_high_per_day": 0.12, "speed_critical_per_day": 0.20}, "telemetry": {"rh_max": 85, "rh_min": 20, "temp_max": 40, "temp_min": 5, "pressure_max": 1050, "pressure_min": 950}, "window_days": 5, "alert_levels": {"danger": {"rh": 83, "mgi": 0.65, "temp": 38}, "warning": {"rh": 80, "mgi": 0.50, "temp": 35}, "critical": {"rh": 85, "mgi": 0.80, "temp": 40}}}'::jsonb,
  channels jsonb NOT NULL DEFAULT '{"sms": {"enabled": false, "numbers": [], "alert_levels": ["danger", "critical"]}, "email": {"enabled": true, "addresses": [], "alert_levels": ["warning", "danger", "critical"]}, "in_app": {"enabled": true, "alert_levels": ["warning", "danger", "critical"]}, "webhook": {"url": null, "enabled": false, "alert_levels": ["critical"]}}'::jsonb,
  quiet_hours jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT company_alert_prefs_pkey PRIMARY KEY (company_id),
  CONSTRAINT company_alert_prefs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.custom_reports (
  report_id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  created_by_user_id uuid NOT NULL,
  company_id uuid NOT NULL,
  program_id uuid,
  configuration jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT custom_reports_pkey PRIMARY KEY (report_id),
  CONSTRAINT custom_reports_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT custom_reports_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT custom_reports_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id)
);
CREATE TABLE public.device_ack_log (
  ack_id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL,
  device_mac text NOT NULL,
  image_name text NOT NULL,
  image_id uuid,
  ack_type text NOT NULL CHECK (ack_type = ANY (ARRAY['ACK_OK'::text, 'MISSING_CHUNKS'::text, 'RETRY_COMMAND'::text])),
  next_wake_time timestamp with time zone,
  missing_chunks ARRAY,
  missing_count integer,
  mqtt_topic text NOT NULL,
  mqtt_payload jsonb NOT NULL,
  mqtt_success boolean DEFAULT true,
  mqtt_error text,
  published_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  program_id uuid,
  site_id uuid,
  CONSTRAINT device_ack_log_pkey PRIMARY KEY (ack_id),
  CONSTRAINT device_ack_log_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id),
  CONSTRAINT device_ack_log_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.device_images(image_id),
  CONSTRAINT device_ack_log_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT device_ack_log_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.device_alert_thresholds (
  threshold_config_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  device_id uuid CHECK (device_id IS NULL OR device_id IS NOT NULL),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by_user_id uuid,
  updated_by_user_id uuid,
  temp_min_warning numeric DEFAULT 32.0,
  temp_min_critical numeric DEFAULT 25.0,
  temp_max_warning numeric DEFAULT 90.0,
  temp_max_critical numeric DEFAULT 100.0,
  rh_min_warning numeric DEFAULT 20.0,
  rh_min_critical numeric DEFAULT 10.0,
  rh_max_warning numeric DEFAULT 80.0,
  rh_max_critical numeric DEFAULT 90.0,
  mgi_max_warning numeric DEFAULT 70.0,
  mgi_max_critical numeric DEFAULT 85.0,
  temp_shift_min_per_session numeric DEFAULT '-25.0'::numeric,
  temp_shift_max_per_session numeric DEFAULT 25.0,
  rh_shift_min_per_session numeric DEFAULT '-50.0'::numeric,
  rh_shift_max_per_session numeric DEFAULT 50.0,
  mgi_velocity_warning numeric DEFAULT 30.0,
  mgi_velocity_critical numeric DEFAULT 40.0,
  mgi_speed_per_day_warning numeric DEFAULT 5.0,
  mgi_speed_per_day_critical numeric DEFAULT 7.0,
  mgi_speed_per_week_warning numeric DEFAULT 10.0,
  mgi_speed_per_week_critical numeric DEFAULT 15.0,
  combo_zone_warning jsonb DEFAULT '{"rh_threshold": 75, "temp_threshold": 60}'::jsonb,
  combo_zone_critical jsonb DEFAULT '{"rh_threshold": 75, "temp_threshold": 70}'::jsonb,
  CONSTRAINT device_alert_thresholds_pkey PRIMARY KEY (threshold_config_id),
  CONSTRAINT device_alert_thresholds_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT device_alert_thresholds_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id),
  CONSTRAINT device_alert_thresholds_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT device_alert_thresholds_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.device_alerts (
  alert_id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL,
  alert_type text NOT NULL CHECK (alert_type = ANY (ARRAY['missed_wake'::text, 'low_battery'::text, 'connection_failure'::text, 'sensor_error'::text, 'image_transmission_failed'::text, 'prolonged_offline'::text, 'firmware_outdated'::text, 'storage_full'::text])),
  severity text DEFAULT 'warning'::text CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'error'::text, 'critical'::text])),
  message text NOT NULL,
  metadata jsonb,
  triggered_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone,
  resolved_by_user_id uuid,
  resolution_notes text,
  notification_sent boolean DEFAULT false,
  company_id uuid,
  program_id uuid,
  site_id uuid,
  alert_category text CHECK (alert_category = ANY (ARRAY['absolute'::text, 'shift'::text, 'velocity'::text, 'speed'::text, 'combination'::text, 'system'::text])),
  device_coords text,
  zone_label text,
  site_name text,
  program_name text,
  company_name text,
  threshold_context jsonb DEFAULT '{}'::jsonb,
  actual_value numeric,
  threshold_value numeric,
  measurement_timestamp timestamp with time zone,
  CONSTRAINT device_alerts_pkey PRIMARY KEY (alert_id),
  CONSTRAINT device_alerts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT device_alerts_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id),
  CONSTRAINT device_alerts_resolved_by_user_id_fkey FOREIGN KEY (resolved_by_user_id) REFERENCES public.users(id),
  CONSTRAINT device_alerts_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT device_alerts_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.device_commands (
  command_id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL,
  command_type text NOT NULL CHECK (command_type = ANY (ARRAY['retry_image'::text, 'capture_image'::text, 'send_image'::text, 'set_wake_schedule'::text, 'update_config'::text, 'reboot'::text, 'update_firmware'::text, 'resend_chunks'::text])),
  command_payload jsonb,
  issued_at timestamp with time zone NOT NULL DEFAULT now(),
  delivered_at timestamp with time zone,
  acknowledged_at timestamp with time zone,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'published'::text, 'acknowledged'::text, 'completed'::text, 'failed'::text, 'expired'::text, 'cancelled'::text])),
  retry_count integer DEFAULT 0,
  created_by_user_id uuid,
  notes text,
  priority integer DEFAULT 5 CHECK (priority >= 1 AND priority <= 10),
  scheduled_for timestamp with time zone,
  published_at timestamp with time zone,
  completed_at timestamp with time zone,
  expires_at timestamp with time zone,
  max_retries integer DEFAULT 3,
  error_message text,
  company_id uuid,
  program_id uuid,
  site_id uuid,
  CONSTRAINT device_commands_pkey PRIMARY KEY (command_id),
  CONSTRAINT device_commands_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT device_commands_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id),
  CONSTRAINT device_commands_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT device_commands_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT device_commands_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.device_error_codes (
  error_code integer NOT NULL,
  error_category text NOT NULL,
  error_message text NOT NULL,
  severity USER-DEFINED NOT NULL DEFAULT 'error'::event_severity,
  recommended_action text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT device_error_codes_pkey PRIMARY KEY (error_code)
);
CREATE TABLE public.device_history (
  history_id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL,
  site_id uuid,
  program_id uuid,
  session_id uuid,
  event_category USER-DEFINED NOT NULL,
  event_type text NOT NULL,
  severity USER-DEFINED NOT NULL DEFAULT 'info'::event_severity,
  event_timestamp timestamp with time zone NOT NULL DEFAULT now(),
  event_data jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  user_id uuid,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  source_table text,
  source_id uuid,
  triggered_by text DEFAULT 'system'::text,
  CONSTRAINT device_history_pkey PRIMARY KEY (history_id),
  CONSTRAINT device_history_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id),
  CONSTRAINT device_history_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT device_history_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT device_history_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.device_wake_sessions(session_id),
  CONSTRAINT device_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT device_history_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.device_images (
  image_id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL,
  image_name text NOT NULL,
  image_url text,
  image_size integer,
  captured_at timestamp with time zone NOT NULL,
  received_at timestamp with time zone,
  total_chunks integer,
  received_chunks integer DEFAULT 0,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'receiving'::text, 'complete'::text, 'failed'::text])),
  error_code integer DEFAULT 0,
  retry_count integer DEFAULT 0,
  submission_id uuid,
  observation_id uuid,
  observation_type text CHECK (observation_type = ANY (ARRAY['petri'::text, 'gasifier'::text])),
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  max_retries integer DEFAULT 3,
  failed_at timestamp with time zone,
  timeout_reason text,
  company_id uuid,
  resent_received_at timestamp with time zone,
  original_capture_date date,
  program_id uuid,
  site_id uuid,
  site_device_session_id uuid,
  mgi_score numeric CHECK (mgi_score >= 0::numeric AND mgi_score <= 1::numeric),
  mold_growth_velocity numeric,
  mold_growth_speed numeric,
  CONSTRAINT device_images_pkey PRIMARY KEY (image_id),
  CONSTRAINT device_images_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT device_images_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id),
  CONSTRAINT device_images_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT device_images_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT device_images_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT device_images_site_device_session_id_fkey FOREIGN KEY (site_device_session_id) REFERENCES public.site_device_sessions(session_id)
);
CREATE TABLE public.device_program_assignments (
  assignment_id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL,
  program_id uuid NOT NULL,
  is_primary boolean DEFAULT false,
  is_active boolean DEFAULT true,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  assigned_by_user_id uuid,
  unassigned_at timestamp with time zone,
  unassigned_by_user_id uuid,
  reason text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  CONSTRAINT device_program_assignments_pkey PRIMARY KEY (assignment_id),
  CONSTRAINT device_program_assignments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT device_program_assignments_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id),
  CONSTRAINT device_program_assignments_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT device_program_assignments_assigned_by_user_id_fkey FOREIGN KEY (assigned_by_user_id) REFERENCES public.users(id),
  CONSTRAINT device_program_assignments_unassigned_by_user_id_fkey FOREIGN KEY (unassigned_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.device_schedule_changes (
  change_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  device_id uuid NOT NULL,
  new_wake_schedule_cron text NOT NULL,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  requested_by_user_id uuid,
  effective_date date NOT NULL,
  applied_at timestamp with time zone,
  applied_by_function text,
  CONSTRAINT device_schedule_changes_pkey PRIMARY KEY (change_id),
  CONSTRAINT device_schedule_changes_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT device_schedule_changes_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id),
  CONSTRAINT device_schedule_changes_requested_by_user_id_fkey FOREIGN KEY (requested_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.device_site_assignments (
  assignment_id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL,
  site_id uuid NOT NULL,
  program_id uuid NOT NULL,
  is_primary boolean DEFAULT false,
  is_active boolean DEFAULT true,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  assigned_by_user_id uuid,
  unassigned_at timestamp with time zone,
  unassigned_by_user_id uuid,
  reason text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  CONSTRAINT device_site_assignments_pkey PRIMARY KEY (assignment_id),
  CONSTRAINT device_site_assignments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT device_site_assignments_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id),
  CONSTRAINT device_site_assignments_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT device_site_assignments_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT device_site_assignments_assigned_by_user_id_fkey FOREIGN KEY (assigned_by_user_id) REFERENCES public.users(id),
  CONSTRAINT device_site_assignments_unassigned_by_user_id_fkey FOREIGN KEY (unassigned_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.device_telemetry (
  telemetry_id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL,
  captured_at timestamp with time zone NOT NULL,
  temperature numeric,
  humidity numeric CHECK (humidity >= 0::numeric AND humidity <= 100::numeric),
  pressure numeric,
  gas_resistance numeric,
  battery_voltage numeric,
  wifi_rssi integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  program_id uuid,
  site_id uuid,
  site_device_session_id uuid,
  CONSTRAINT device_telemetry_pkey PRIMARY KEY (telemetry_id),
  CONSTRAINT device_telemetry_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT device_telemetry_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id),
  CONSTRAINT device_telemetry_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT device_telemetry_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT device_telemetry_site_device_session_id_fkey FOREIGN KEY (site_device_session_id) REFERENCES public.site_device_sessions(session_id)
);
CREATE TABLE public.device_wake_payloads (
  payload_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  program_id uuid NOT NULL,
  site_id uuid NOT NULL,
  site_device_session_id uuid NOT NULL,
  device_id uuid NOT NULL,
  captured_at timestamp with time zone NOT NULL,
  received_at timestamp with time zone,
  wake_window_index integer,
  image_id uuid,
  image_status text CHECK (image_status = ANY (ARRAY['pending'::text, 'receiving'::text, 'complete'::text, 'failed'::text])),
  resent_received_at timestamp with time zone,
  temperature numeric,
  humidity numeric,
  pressure numeric,
  gas_resistance numeric,
  battery_voltage numeric,
  wifi_rssi integer,
  telemetry_data jsonb,
  payload_status text DEFAULT 'pending'::text CHECK (payload_status = ANY (ARRAY['pending'::text, 'complete'::text, 'failed'::text])),
  overage_flag boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT device_wake_payloads_pkey PRIMARY KEY (payload_id),
  CONSTRAINT device_wake_payloads_site_device_session_id_fkey FOREIGN KEY (site_device_session_id) REFERENCES public.site_device_sessions(session_id),
  CONSTRAINT device_wake_payloads_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id),
  CONSTRAINT device_wake_payloads_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.device_images(image_id),
  CONSTRAINT device_wake_payloads_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT device_wake_payloads_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT device_wake_payloads_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.device_wake_sessions (
  session_id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL,
  site_id uuid,
  program_id uuid,
  wake_timestamp timestamp with time zone NOT NULL DEFAULT now(),
  session_duration_ms integer,
  next_wake_scheduled timestamp with time zone,
  connection_success boolean DEFAULT false,
  wifi_retry_count integer DEFAULT 0,
  mqtt_connected boolean DEFAULT false,
  image_captured boolean DEFAULT false,
  image_id uuid,
  chunks_sent integer DEFAULT 0,
  chunks_total integer DEFAULT 0,
  chunks_missing ARRAY DEFAULT ARRAY[]::integer[],
  transmission_complete boolean DEFAULT false,
  telemetry_data jsonb DEFAULT '{}'::jsonb,
  status USER-DEFINED DEFAULT 'in_progress'::device_session_status,
  error_codes ARRAY DEFAULT ARRAY[]::text[],
  pending_images_count integer DEFAULT 0,
  was_offline_capture boolean DEFAULT false,
  offline_duration_hours numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  wake_variance_minutes integer,
  CONSTRAINT device_wake_sessions_pkey PRIMARY KEY (session_id),
  CONSTRAINT device_wake_sessions_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id),
  CONSTRAINT device_wake_sessions_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT device_wake_sessions_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT device_wake_sessions_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.device_images(image_id),
  CONSTRAINT device_wake_sessions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.devices (
  device_id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_mac text NOT NULL UNIQUE,
  device_name text,
  site_id uuid,
  program_id uuid,
  firmware_version text,
  hardware_version text DEFAULT 'ESP32-S3'::text,
  is_active boolean DEFAULT true,
  last_seen_at timestamp with time zone,
  last_wake_at timestamp with time zone,
  next_wake_at timestamp with time zone,
  wake_schedule_cron text,
  battery_voltage numeric,
  battery_health_percent integer CHECK (battery_health_percent >= 0 AND battery_health_percent <= 100),
  wifi_ssid text,
  mqtt_client_id text,
  provisioned_at timestamp with time zone,
  provisioned_by_user_id uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  mapped_at timestamp with time zone,
  mapped_by_user_id uuid,
  provisioning_status text DEFAULT 'pending_mapping'::text CHECK (provisioning_status = ANY (ARRAY['pending_approval'::text, 'pending_mapping'::text, 'mapped'::text, 'active'::text, 'inactive'::text, 'decommissioned'::text, 'system'::text])),
  device_reported_site_id text,
  device_reported_location text,
  device_code text UNIQUE,
  company_id uuid,
  x_position numeric,
  y_position numeric,
  zone_id uuid,
  zone_label text,
  placement_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  device_type text DEFAULT 'physical'::text CHECK (device_type = ANY (ARRAY['physical'::text, 'virtual'::text])),
  wifi_rssi integer,
  last_updated_by_user_id uuid,
  battery_critical_threshold numeric DEFAULT 3.4,
  battery_warning_threshold numeric DEFAULT 3.6,
  last_wake_variance_minutes integer,
  total_wakes integer DEFAULT 0,
  total_alerts integer DEFAULT 0,
  total_battery_health_alerts integer DEFAULT 0,
  total_images_taken integer DEFAULT 0,
  total_images_expected_to_date integer DEFAULT 0,
  next_program_id uuid,
  next_site_id uuid,
  program_expiry_alert_sent boolean DEFAULT false,
  is_overtime_mode boolean DEFAULT false,
  CONSTRAINT devices_pkey PRIMARY KEY (device_id),
  CONSTRAINT devices_mapped_by_user_id_fkey FOREIGN KEY (mapped_by_user_id) REFERENCES public.users(id),
  CONSTRAINT devices_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT devices_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT devices_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT devices_provisioned_by_user_id_fkey FOREIGN KEY (provisioned_by_user_id) REFERENCES public.users(id),
  CONSTRAINT devices_next_program_id_fkey FOREIGN KEY (next_program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT devices_next_site_id_fkey FOREIGN KEY (next_site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.edge_chunk_buffer (
  chunk_key text NOT NULL,
  device_mac text NOT NULL,
  image_name text NOT NULL,
  chunk_index integer NOT NULL,
  chunk_data ARRAY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  CONSTRAINT edge_chunk_buffer_pkey PRIMARY KEY (chunk_key)
);
CREATE TABLE public.gasifier_observations (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  gasifier_code text NOT NULL,
  image_url text,
  chemical_type USER-DEFINED NOT NULL DEFAULT 'Citronella Blend'::chemical_type_enum,
  measure numeric CHECK (measure >= 0::numeric AND measure <= 10::numeric),
  anomaly boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lastupdated_by uuid,
  program_id uuid,
  placement_height USER-DEFINED,
  directional_placement USER-DEFINED,
  placement_strategy USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  order_index integer,
  position_x numeric,
  position_y numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric CHECK (footage_from_origin_x >= 0::numeric),
  footage_from_origin_y numeric DEFAULT '0'::numeric CHECK (footage_from_origin_y >= 0::numeric),
  linear_reading real,
  linear_reduction_nominal real DEFAULT '6'::real CHECK (linear_reduction_nominal < 6.01::double precision),
  linear_reduction_per_day real DEFAULT '6'::real CHECK (linear_reduction_per_day < 6.1::double precision),
  flow_rate real DEFAULT '6'::real,
  flag_for_review boolean DEFAULT false,
  daysinthisprogramphase numeric DEFAULT 0,
  todays_day_of_phase numeric DEFAULT 0,
  yesterday_reading numeric DEFAULT '6'::numeric,
  company_id uuid,
  is_device_generated boolean DEFAULT false,
  device_capture_metadata jsonb,
  CONSTRAINT gasifier_observations_pkey PRIMARY KEY (observation_id),
  CONSTRAINT gasifier_observations_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT gasifier_observations_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT gasifier_observations_lastupdated_by_fkey FOREIGN KEY (lastupdated_by) REFERENCES auth.users(id),
  CONSTRAINT gasifier_observations_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT gasifier_observations_last_updated_by_user_id_fkey FOREIGN KEY (last_updated_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT gasifier_observations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.mcp_context_tracking (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  contextual_update text,
  planning_doc text,
  context_and_plan_progress_with_timestamps text,
  CONSTRAINT mcp_context_tracking_pkey PRIMARY KEY (id)
);
CREATE TABLE public.petri_observations (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric CHECK (growth_index < 11::numeric),
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric CHECK (footage_from_origin_x >= 0::numeric),
  footage_from_origin_y numeric DEFAULT 0 CHECK (footage_from_origin_y >= 0::numeric),
  growth_progression numeric DEFAULT 0.00 CHECK (growth_progression >= 0::numeric),
  growth_aggression numeric DEFAULT 0.00 CHECK (growth_aggression >= '-1000'::integer::numeric),
  growth_velocity real,
  daysInThisProgramPhase numeric,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  daysinthisprogramphase numeric DEFAULT 1,
  is_device_generated boolean DEFAULT false,
  device_capture_metadata jsonb,
  company_id uuid,
  mgi_score numeric CHECK (mgi_score >= 0::numeric AND mgi_score <= 1::numeric),
  mgi_confidence numeric CHECK (mgi_confidence >= 0::numeric AND mgi_confidence <= 1::numeric),
  mgi_scored_at timestamp with time zone,
  CONSTRAINT petri_observations_pkey PRIMARY KEY (observation_id),
  CONSTRAINT petri_observations_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT petri_observations_lastupdated_by_fkey FOREIGN KEY (lastupdated_by) REFERENCES auth.users(id),
  CONSTRAINT petri_observations_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_last_updated_by_user_id_fkey FOREIGN KEY (last_updated_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT petri_observations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT petri_observations_main_petri_id_fkey FOREIGN KEY (main_petri_id) REFERENCES public.petri_observations(observation_id)
);
CREATE TABLE public.pilot_program_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_timestamp timestamp with time zone NOT NULL DEFAULT now(),
  update_type USER-DEFINED NOT NULL,
  object_id uuid NOT NULL,
  object_type text NOT NULL,
  program_id uuid,
  user_id uuid,
  user_email text,
  user_company text,
  user_role text,
  old_data jsonb,
  new_data jsonb,
  ip_address text,
  user_agent text,
  company_id uuid,
  CONSTRAINT pilot_program_history_pkey PRIMARY KEY (id),
  CONSTRAINT pilot_program_history_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.pilot_program_history_staging (
  id uuid,
  event_timestamp timestamp with time zone,
  update_type text,
  object_id uuid,
  object_type text,
  program_id uuid,
  user_id uuid,
  user_email text,
  user_company text,
  user_role text,
  old_data jsonb,
  new_data jsonb,
  ip_address text,
  user_agent text,
  company_id uuid
);
CREATE TABLE public.pilot_program_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'Edit'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_email character varying,
  CONSTRAINT pilot_program_users_pkey PRIMARY KEY (id),
  CONSTRAINT pilot_program_users_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT pilot_program_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.pilot_program_users_archive (
  id uuid,
  program_id uuid,
  user_id uuid,
  role text,
  created_at timestamp with time zone,
  user_email character varying,
  archived_at timestamp with time zone DEFAULT now(),
  archived_reason text DEFAULT 'Removed due to RLS rebuild - access now controlled by company membership and user_role'::text
);
CREATE TABLE public.pilot_programs (
  program_id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status USER-DEFINED NOT NULL,
  total_submissions integer DEFAULT 0,
  total_sites integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lastupdated_by uuid,
  company_id uuid,
  cloned_from_program_id uuid,
  phases jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT pilot_programs_pkey PRIMARY KEY (program_id),
  CONSTRAINT pilot_programs_lastupdated_by_fkey FOREIGN KEY (lastupdated_by) REFERENCES auth.users(id),
  CONSTRAINT pilot_programs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT pilot_programs_cloned_from_program_id_fkey FOREIGN KEY (cloned_from_program_id) REFERENCES public.pilot_programs(program_id)
);
CREATE TABLE public.report_subscriptions (
  subscription_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  user_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['weekly_digest'::text, 'daily_rollup'::text, 'threshold_alerts'::text, 'mgi_trends'::text, 'zone_comparison'::text])),
  filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  schedule text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  last_sent_at timestamp with time zone,
  next_scheduled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_subscriptions_pkey PRIMARY KEY (subscription_id),
  CONSTRAINT report_subscriptions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT report_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.session_creation_log (
  log_id uuid NOT NULL DEFAULT gen_random_uuid(),
  execution_time timestamp with time zone NOT NULL DEFAULT now(),
  total_sites integer DEFAULT 0,
  success_count integer DEFAULT 0,
  error_count integer DEFAULT 0,
  details jsonb,
  execution_duration_ms integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT session_creation_log_pkey PRIMARY KEY (log_id)
);
CREATE TABLE public.site_device_sessions (
  session_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  program_id uuid NOT NULL,
  site_id uuid NOT NULL,
  session_date date NOT NULL,
  session_start_time timestamp with time zone NOT NULL,
  session_end_time timestamp with time zone NOT NULL,
  expected_wake_count integer NOT NULL DEFAULT 0,
  completed_wake_count integer DEFAULT 0,
  failed_wake_count integer DEFAULT 0,
  extra_wake_count integer DEFAULT 0,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'locked'::text])),
  config_changed_flag boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  locked_at timestamp with time zone,
  device_submission_id uuid,
  CONSTRAINT site_device_sessions_pkey PRIMARY KEY (session_id),
  CONSTRAINT site_device_sessions_device_submission_id_fkey FOREIGN KEY (device_submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT site_device_sessions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT site_device_sessions_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT site_device_sessions_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.site_program_assignments (
  assignment_id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL,
  program_id uuid NOT NULL,
  is_primary boolean DEFAULT true,
  is_active boolean DEFAULT true,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  assigned_by_user_id uuid,
  unassigned_at timestamp with time zone,
  unassigned_by_user_id uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  CONSTRAINT site_program_assignments_pkey PRIMARY KEY (assignment_id),
  CONSTRAINT site_program_assignments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT site_program_assignments_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT site_program_assignments_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT site_program_assignments_assigned_by_user_id_fkey FOREIGN KEY (assigned_by_user_id) REFERENCES public.users(id),
  CONSTRAINT site_program_assignments_unassigned_by_user_id_fkey FOREIGN KEY (unassigned_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.site_snapshots (
  snapshot_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  program_id uuid NOT NULL,
  site_id uuid NOT NULL,
  site_code bigint NOT NULL,
  phase_descriptor character varying,
  snapshot_date date NOT NULL,
  placements_snapshot jsonb DEFAULT '{}'::jsonb,
  airflow_snapshot jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  day_number integer NOT NULL DEFAULT 1,
  snapshot_sequence integer DEFAULT 1,
  risk_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT site_snapshots_pkey PRIMARY KEY (snapshot_id),
  CONSTRAINT site_snapshots_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT site_snapshots_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT site_snapshots_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.sites (
  site_id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  name character varying NOT NULL,
  type USER-DEFINED NOT NULL,
  total_petris integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  submission_defaults jsonb,
  petri_defaults jsonb DEFAULT '[]'::jsonb,
  default_temperature numeric,
  default_humidity numeric,
  default_weather USER-DEFINED,
  default_indoor_temperature numeric CHECK (default_indoor_temperature >= 32::numeric AND default_indoor_temperature <= 120::numeric),
  default_indoor_humidity numeric CHECK (default_indoor_humidity >= 1::numeric AND default_indoor_humidity <= 100::numeric),
  gasifier_defaults jsonb DEFAULT '[]'::jsonb,
  total_gasifiers integer DEFAULT 0,
  square_footage numeric CHECK (square_footage >= 100::numeric AND square_footage <= 1000000000::numeric),
  cubic_footage numeric CHECK (cubic_footage >= 25::numeric AND cubic_footage <= 1000000::numeric),
  num_vents integer CHECK (num_vents >= 1 AND num_vents <= 10000),
  vent_placements ARRAY,
  primary_function USER-DEFINED,
  construction_material USER-DEFINED,
  insulation_type USER-DEFINED,
  hvac_system_present boolean DEFAULT false,
  hvac_system_type USER-DEFINED,
  irrigation_system_type USER-DEFINED,
  lighting_system USER-DEFINED,
  length numeric,
  width numeric,
  height numeric,
  min_efficacious_gasifier_density_sqft_per_bag numeric DEFAULT 2000,
  recommended_placement_density_bags integer,
  has_dead_zones boolean DEFAULT false,
  num_regularly_opened_ports integer,
  state text,
  country text,
  timezone text,
  interior_working_surface_types ARRAY,
  microbial_risk_zone USER-DEFINED DEFAULT 'Medium'::microbial_risk_zone_enum,
  quantity_deadzones integer CHECK (quantity_deadzones IS NULL OR quantity_deadzones >= 1 AND quantity_deadzones <= 25),
  ventilation_strategy USER-DEFINED,
  site_code bigint,
  Number of Fans integer CHECK ("Number of Fans" < 51),
  airflow_vectors jsonb DEFAULT '[]'::jsonb,
  door_details jsonb DEFAULT '[]'::jsonb,
  number_of_platforms smallint DEFAULT '0'::smallint,
  platform_details jsonb DEFAULT '[]'::jsonb,
  company_id uuid,
  fan_details jsonb,
  wall_details jsonb DEFAULT '[{"wall_id": "north_wall", "material": "Polycarbonate", "end_point": {"x": 110, "y": 0}, "length_ft": 110, "orientation": "North", "start_point": {"x": 0, "y": 0}, "justification": "outside"}, {"wall_id": "east_wall", "material": "Polycarbonate", "end_point": {"x": 110, "y": 100}, "length_ft": 100, "orientation": "East", "start_point": {"x": 110, "y": 0}, "justification": "outside"}, {"wall_id": "south_wall", "material": "Polycarbonate", "end_point": {"x": 0, "y": 100}, "length_ft": 110, "orientation": "South", "start_point": {"x": 110, "y": 100}, "justification": "outside"}, {"wall_id": "west_wall", "material": "Polycarbonate", "end_point": {"x": 0, "y": 0}, "length_ft": 100, "orientation": "West", "start_point": {"x": 0, "y": 100}, "justification": "outside"}]'::jsonb,
  zones jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT sites_pkey PRIMARY KEY (site_id),
  CONSTRAINT sites_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT sites_lastupdated_by_fkey FOREIGN KEY (lastupdated_by) REFERENCES auth.users(id),
  CONSTRAINT sites_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.split_petri_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_image_url text NOT NULL,
  main_petri_observation_id uuid NOT NULL,
  archived_at timestamp with time zone DEFAULT now(),
  processed_by_user_id uuid,
  CONSTRAINT split_petri_images_pkey PRIMARY KEY (id),
  CONSTRAINT split_petri_images_main_petri_observation_id_fkey FOREIGN KEY (main_petri_observation_id) REFERENCES public.petri_observations(observation_id),
  CONSTRAINT split_petri_images_processed_by_user_id_fkey FOREIGN KEY (processed_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.submission_sessions (
  session_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL UNIQUE,
  site_id uuid NOT NULL,
  program_id uuid NOT NULL,
  opened_by_user_id uuid,
  session_start_time timestamp with time zone NOT NULL DEFAULT now(),
  last_activity_time timestamp with time zone NOT NULL DEFAULT now(),
  session_status USER-DEFINED NOT NULL DEFAULT 'Opened'::session_status_enum,
  completion_time timestamp with time zone,
  completed_by_user_id uuid,
  percentage_complete numeric NOT NULL DEFAULT 0.00,
  valid_petris_logged integer NOT NULL DEFAULT 0,
  valid_gasifiers_logged integer NOT NULL DEFAULT 0,
  escalated_to_user_ids ARRAY,
  company_id uuid,
  CONSTRAINT submission_sessions_pkey PRIMARY KEY (session_id),
  CONSTRAINT submission_sessions_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT submission_sessions_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT submission_sessions_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT submission_sessions_opened_by_user_id_fkey FOREIGN KEY (opened_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT submission_sessions_completed_by_user_id_fkey FOREIGN KEY (completed_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT submission_sessions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.submissions (
  submission_id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL,
  program_id uuid NOT NULL,
  temperature numeric NOT NULL,
  humidity numeric NOT NULL DEFAULT NULL::numeric,
  airflow USER-DEFINED NOT NULL,
  odor_distance USER-DEFINED NOT NULL,
  weather USER-DEFINED NOT NULL,
  notes character varying,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name text,
  lastupdated_by uuid,
  indoor_temperature numeric CHECK (indoor_temperature >= 32::numeric AND indoor_temperature <= 120::numeric),
  indoor_humidity numeric CHECK (indoor_humidity >= 1::numeric AND indoor_humidity <= 100::numeric),
  global_submission_id bigint NOT NULL UNIQUE,
  submission_timezone text,
  company_id uuid,
  forecasted_expiration timestamp without time zone,
  trend_gasifier_velocity USER-DEFINED,
  yesterday_reading numeric DEFAULT '6'::numeric,
  indoor_humidity_new numeric CHECK (indoor_humidity_new >= 1::numeric AND indoor_humidity_new <= 100::numeric),
  created_by_device_id uuid,
  is_device_generated boolean DEFAULT false,
  CONSTRAINT submissions_pkey PRIMARY KEY (submission_id),
  CONSTRAINT submissions_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT submissions_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT submissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT submissions_lastupdated_by_fkey FOREIGN KEY (lastupdated_by) REFERENCES auth.users(id),
  CONSTRAINT submissions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT submissions_created_by_device_id_fkey FOREIGN KEY (created_by_device_id) REFERENCES public.devices(device_id)
);
CREATE TABLE public.superadmin_impersonations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  super_admin_user_id uuid NOT NULL,
  target_company_id uuid NOT NULL,
  target_company_name text,
  reason text NOT NULL,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  was_global_override boolean NOT NULL DEFAULT false,
  request_ip text,
  user_agent text,
  CONSTRAINT superadmin_impersonations_pkey PRIMARY KEY (id),
  CONSTRAINT superadmin_impersonations_super_admin_user_id_fkey FOREIGN KEY (super_admin_user_id) REFERENCES auth.users(id),
  CONSTRAINT superadmin_impersonations_target_company_id_fkey FOREIGN KEY (target_company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.system_users (
  system_user_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  system_name text NOT NULL DEFAULT 'System'::text,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_users_pkey PRIMARY KEY (system_user_id)
);
CREATE TABLE public.user_active_company_context (
  user_id uuid NOT NULL,
  active_company_id uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_active_company_context_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_active_company_context_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_active_company_context_active_company_id_fkey FOREIGN KEY (active_company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  company text,
  avatar_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  is_company_admin boolean NOT NULL DEFAULT false,
  is_super_admin boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  user_role USER-DEFINED NOT NULL DEFAULT 'observer'::user_role,
  export_rights USER-DEFINED NOT NULL DEFAULT 'None'::export_rights,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);