/*
  # Add Protocol State Tracking to Wake Payloads

  1. New Columns
    - protocol_state: Track current state in ESP32-CAM MQTT protocol flow
    - server_image_name: Image name generated by server
    - ack_sent_at, snap_sent_at, sleep_sent_at: Protocol timing

  2. Protocol States
    - hello_received: Device sent HELLO
    - ack_sent: Server sent ACK
    - snap_sent: Server sent SNAP command
    - metadata_received: Got metadata, receiving chunks
    - complete: Image complete, SLEEP sent
    - failed: Protocol flow failed
    - sleep_only: Just send SLEEP (no schedule/unmapped)
*/

-- Add protocol state tracking columns
ALTER TABLE device_wake_payloads
ADD COLUMN IF NOT EXISTS protocol_state TEXT
  CHECK (protocol_state IN (
    'hello_received',
    'ack_sent',
    'snap_sent',
    'metadata_received',
    'complete',
    'failed',
    'sleep_only'
  ));

ALTER TABLE device_wake_payloads
ADD COLUMN IF NOT EXISTS server_image_name TEXT;

ALTER TABLE device_wake_payloads
ADD COLUMN IF NOT EXISTS ack_sent_at TIMESTAMPTZ;

ALTER TABLE device_wake_payloads
ADD COLUMN IF NOT EXISTS snap_sent_at TIMESTAMPTZ;

ALTER TABLE device_wake_payloads
ADD COLUMN IF NOT EXISTS sleep_sent_at TIMESTAMPTZ;

-- Create index for protocol state queries
CREATE INDEX IF NOT EXISTS idx_device_wake_payloads_protocol_state
  ON device_wake_payloads(protocol_state, device_id, captured_at DESC);

-- Migrate existing data
UPDATE device_wake_payloads
SET protocol_state = 'complete'
WHERE protocol_state IS NULL
  AND image_status = 'complete'
  AND image_id IS NOT NULL;

UPDATE device_wake_payloads
SET protocol_state = 'failed'
WHERE protocol_state IS NULL
  AND image_status = 'failed';

UPDATE device_wake_payloads
SET protocol_state = 'metadata_received'
WHERE protocol_state IS NULL
  AND image_status = 'receiving';

UPDATE device_wake_payloads
SET protocol_state = 'complete'
WHERE protocol_state IS NULL
  AND payload_status = 'complete'
  AND (image_id IS NULL OR image_status IS NULL);

UPDATE device_wake_payloads
SET protocol_state = 'hello_received'
WHERE protocol_state IS NULL;

-- Add comments
COMMENT ON COLUMN device_wake_payloads.protocol_state IS 'Current state in device wake protocol flow';
COMMENT ON COLUMN device_wake_payloads.server_image_name IS 'Server-assigned image filename for tracking';
COMMENT ON COLUMN device_wake_payloads.ack_sent_at IS 'Timestamp when ACK was sent to device';
COMMENT ON COLUMN device_wake_payloads.snap_sent_at IS 'Timestamp when SNAP command was sent';
COMMENT ON COLUMN device_wake_payloads.sleep_sent_at IS 'Timestamp when SLEEP command was sent';
